// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220712184158_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "RPG",
                            ImageUrl = "https://a.allegroimg.com/original/03ef7f/a2f7f1f44518b44e400e834745c6/THE-WITCHER-3-WILD-HUNT-PL-GOG-KLUCZ-GRATIS",
                            Price = 9.99m,
                            Title = "Wiedźmin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Horror",
                            ImageUrl = "https://assets.reedpopcdn.com/dead_space_remake_felieton.jpg/BROK/thumbnail/1200x1200/quality/100/dead_space_remake_felieton.jpg",
                            Price = 7.99m,
                            Title = "Dead Space"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Logic",
                            ImageUrl = "https://a.allegroimg.com/original/11e87f/f56f2f0d47a48ede1ff0300d4549/Factorio-STEAM",
                            Price = 19.99m,
                            Title = "Factorio"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
